version: '3.8'

# Definição de variáveis para fácil customização de domínios
x-environment: &default-env
  # Domínios para os diferentes serviços
  MAIN_DOMAIN: speedfunnels.online
  API_DOMAIN: api.speedfunnels.online
  APP_DOMAIN: app.speedfunnels.online
  # Lista de domínios permitidos para CORS
  CORS_ORIGIN: "https://app.speedfunnels.online,https://speedfunnels.online,https://www.speedfunnels.online,http://localhost:3000"
  # URL do frontend para redirecionamentos
  FRONTEND_URL: "https://app.speedfunnels.online"

services:
  api:
    image: marcussviniciusa/meta-ads-backend:v1.0.48
    # Healthcheck simplificado
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      <<: *default-env
      # Configurações do backend
      PORT: 8080
      NODE_ENV: production
      # Configurações explícitas de CORS para permitir credenciais com origens específicas
      CORS_ENABLED: "true"
      ACCESS_CONTROL_ALLOW_ORIGIN: "https://app.speedfunnels.online"
      CORS_ALLOWED_ORIGINS: "https://app.speedfunnels.online,https://speedfunnels.online,https://www.speedfunnels.online,http://localhost:3000"
      CORS_ALLOWED_METHODS: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
      CORS_ALLOWED_HEADERS: "Origin,X-Requested-With,Content-Type,Accept,Authorization"
      CORS_ALLOW_CREDENTIALS: "true"
      
      # Configurações da integração com Meta
      META_REDIRECT_URI: "https://app.speedfunnels.online/connect-meta/callback"
      META_API_VERSION: "v22.0"
      # Configurações do banco de dados - conectando-se aos serviços existentes
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: meta_ads
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4f4f49cc55e4ba2667873c2e8e97e1d6
      # Configurações Redis - conectando-se aos serviços existentes
      REDIS_HOST: 77.37.41.106
      REDIS_PORT: 6380
      REDIS_PASSWORD: Marcus1911Marcus
      # Meta e Google integrations
      META_APP_ID: 4190441111244279
      META_APP_SECRET: 8ef5ee9f87897877584e8c7f27a2171c
      GOOGLE_CLIENT_ID: 446046495796-ondcr66o2bq9toipem4n8oi9nv1rtua7.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      # Credenciais admin
      JWT_SECRET: 45aab33419d55426e0276078dd8b16eac990c163afab0f20645d976cd92c80eb96
      SUPER_ADMIN_EMAIL: admin@speedfunnels.marcussviniciusa.cloud
      SUPER_ADMIN_PASSWORD: Admin2025!
      MIGRATION_SECRET_KEY: speedfunnels_migration_key
      # Configuração para forçar a migração do banco de dados
      AUTO_MIGRATE: "true"
      RUN_MIGRATIONS: "true"
    ports:
      - "8080:8080"
    networks:
      - SpeedFunnelsNet
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=SpeedFunnelsNet"
        # Roteamento para a API com suporte para ambos HTTP e HTTPS
        - "traefik.http.routers.meta-api.rule=Host(`api.speedfunnels.online`)"
        - "traefik.http.routers.meta-api.entrypoints=web,websecure"
        - "traefik.http.services.meta-api-service.loadbalancer.server.port=8080"
        
        # Configuração separada para HTTP e HTTPS
        # Rota HTTP
        - "traefik.http.routers.meta-api-http.rule=Host(`api.speedfunnels.online`)"
        - "traefik.http.routers.meta-api-http.entrypoints=web"
        - "traefik.http.routers.meta-api-http.service=meta-api-service"
        
        # Rota HTTPS com TLS
        - "traefik.http.routers.meta-api-https.rule=Host(`api.speedfunnels.online`)"
        - "traefik.http.routers.meta-api-https.entrypoints=websecure"
        - "traefik.http.routers.meta-api-https.service=meta-api-service"
        - "traefik.http.routers.meta-api-https.tls=true"
        - "traefik.http.routers.meta-api-https.tls.certresolver=letsencryptresolver"
        
        # Configuração CORS específica para o app.speedfunnels.online
        - "traefik.http.middlewares.cors-api.headers.accessControlAllowOriginList=https://app.speedfunnels.online,https://speedfunnels.online,https://www.speedfunnels.online,http://localhost:3000"
        - "traefik.http.middlewares.cors-api.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
        - "traefik.http.middlewares.cors-api.headers.accessControlAllowHeaders=Origin,X-Requested-With,Content-Type,Accept,Authorization"
        - "traefik.http.middlewares.cors-api.headers.accessControlAllowCredentials=true"
        - "traefik.http.middlewares.cors-api.headers.accessControlMaxAge=86400"
        - "traefik.http.middlewares.cors-api.headers.addVaryHeader=true"
        
        # Aplicando middleware de CORS para ambas as rotas
        - "traefik.http.routers.meta-api-http.middlewares=cors-api@docker"
        - "traefik.http.routers.meta-api-https.middlewares=cors-api@docker"

  frontend:
    image: marcussviniciusa/meta-ads-frontend:v1.0.51
    command: ["nginx", "-g", "daemon off;"]
    stop_grace_period: 1m
    environment:
      <<: *default-env
      NODE_ENV: production
      # Suportando ambos HTTP e HTTPS
      REACT_APP_API_URL: "https://api.speedfunnels.online/api"
      REACT_APP_FACEBOOK_APP_ID: 4190441111244279
    networks:
      - SpeedFunnelsNet
    depends_on:
      - api
    ports:
      - "3000:80"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=SpeedFunnelsNet"
        
        # Configuração separada para HTTP e HTTPS
        # Rota HTTP para o frontend
        - "traefik.http.routers.meta-frontend-http.rule=Host(`app.speedfunnels.online`)"
        - "traefik.http.routers.meta-frontend-http.entrypoints=web"
        - "traefik.http.routers.meta-frontend-http.service=meta-frontend-service"
        
        # Rota HTTPS para o frontend
        - "traefik.http.routers.meta-frontend-https.rule=Host(`app.speedfunnels.online`)"
        - "traefik.http.routers.meta-frontend-https.entrypoints=websecure"
        - "traefik.http.routers.meta-frontend-https.service=meta-frontend-service"
        - "traefik.http.routers.meta-frontend-https.tls=true"
        - "traefik.http.routers.meta-frontend-https.tls.certresolver=letsencryptresolver"
        
        # Configuração explícita do serviço
        - "traefik.http.services.meta-frontend-service.loadbalancer.server.port=80"
        
        # Configuração para o domínio principal (MAIN_DOMAIN)
        # HTTP
        - "traefik.http.routers.meta-main-http.rule=Host(`speedfunnels.online`) || Host(`www.speedfunnels.online`)"
        - "traefik.http.routers.meta-main-http.entrypoints=web"
        - "traefik.http.routers.meta-main-http.service=meta-frontend-service"
        
        # HTTPS
        - "traefik.http.routers.meta-main-https.rule=Host(`speedfunnels.online`) || Host(`www.speedfunnels.online`)"
        - "traefik.http.routers.meta-main-https.entrypoints=websecure"
        - "traefik.http.routers.meta-main-https.service=meta-frontend-service"
        - "traefik.http.routers.meta-main-https.tls=true"
        - "traefik.http.routers.meta-main-https.tls.certresolver=letsencryptresolver"

networks:
  SpeedFunnelsNet:
    external: true